<a href="https://colab.research.google.com/github/mahekgheewala/Numpy_array/blob/main/Basic_of_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy- Numerical Python

Advantages:(compared to list and array)

1) Allow several Mathematical operations.

2) Faster Operations.

In [1]:
import numpy as np

List vs Numpy ----Time Taken

In [2]:
# time taken to measure a particular process(how long it takes to run)
from time import process_time

In [4]:
# TIME TAKEN BY A LIST
python_list = [i for i in range(10000)]
start_time=process_time()
python_list= [i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.001262988999998882


np.array is used to create arrays.

In [6]:
# TIME TAKEN BY NUMPY
np_array = np.array([i for i in range(10000)])
start_time=process_time()
np_array +=5
# same as np_array = np_array +5
end_time=process_time()
print(end_time-start_time)

0.0001638849999991976


Numpy Arrays

In [8]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Creating 1-dimensional Array

In [9]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
a.shape

(4,)

Creating 2-dimensional array

In [12]:
array = np.array([(1,2,3,4),(5,6,7,8)])
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
c = np.array([(1,2,3,4), (5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in Numpy Array (in certain cases we want to initialize arrays with certain values)

Such as in some cases we want all the values to be 0, 1, and so on

In [19]:
# create a numpy array of zeros
# In bracket we need to mention the shape of our array
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
# create numpy array of ones
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
# create array of some particular value
# full function is used to create array of specific value
z = np.full((4,5), 5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [21]:
# Create a identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Create numpy array with random values (here values are b/w 0 and 1)

In [24]:
a = np.random.random((3,4))
print(a)

[[0.4261471  0.72247675 0.5984259  0.56759185]
 [0.87480694 0.48632978 0.55121613 0.59995108]
 [0.99350823 0.03847413 0.54261449 0.44860643]]


Create numpy array with random values-----with integers and within specific range.

In [25]:
a= np.random.randint(10,100,(3,5))
print(a)

[[76 26 74 62 74]
 [97 35 62 92 62]
 [21 88 69 98 25]]


Array of evenly spaced values.

In [33]:
d = np.linspace(10,30,2)
print(d)

AttributeError: 'numpy.ndarray' object has no attribute 'linspace'

occurs because linspace is being called on an ndarray object instead of the numpy module. This happens when you've redefined or overwritten np with a NumPy array, so np is no longer the numpy module.



In [34]:
import numpy as np
np = np.linspace(10,30,2)
print(np)

[10. 30.]


Another Way----specifying step number


In [36]:
import numpy as np
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


Converting list into numpy array.....works with list, tuple, nested sequence, pandas, series, etc

In [37]:
list2 = [1,3,44,56,77]
# Convert particular data type into numpy array
np_array = np.asarray(list2)
print(np_array)

[ 1  3 44 56 77]


Analyzing numpy array (getting various information from it)

In [38]:
c = np.random.randint(10,90,(5,5))
print(c)

[[61 11 62 22 45]
 [32 31 25 89 52]
 [18 20 76 43 30]
 [14 86 53 17 87]
 [49 26 34 28 82]]


In [39]:
# ARRAY DIMENSION
print(c.shape)

(5, 5)


In [40]:
# NUMBER OF DIMENSIONS
print(c.ndim)

2


In [41]:
# NUMBER OF ELEMENTS IN AN ARRAY
print(c.size)

25


In [43]:
import numpy as np

In [45]:
# CHECKING VALUES OF THE DATA TYPE INSIDE THE ARRAY
print(c.dtype)

int64


Mathematical Operations on np array

In [46]:
list1 = [1,2,3,4]
list2 = [4,5,6,7,10]
print(list1+list2)
# HERE BOTH LIST ARE GETTING COMBINED, BUT ADDITION IS NOT HAPPENING.(CONCATE)


[1, 2, 3, 4, 4, 5, 6, 7, 10]


In [47]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))


In [48]:
print(a)
print(b)

[[7 0 9]
 [0 5 9]
 [0 5 2]]
[[16 10 17]
 [18 15 10]
 [11 17 15]]


In [49]:
print(a+b)
# HERE WE ARE GETTING ADDITION OF NUMBERS

[[23 10 26]
 [18 20 19]
 [11 22 17]]


In [50]:
print(np.add(a,b))

[[23 10 26]
 [18 20 19]
 [11 22 17]]


ARRAY MANIPULATION

In [52]:
array = np.random.randint(10,30,(3,3))
print(array)

[[28 25 19]
 [15 13 24]
 [11 23 23]]


In [54]:
# CREATE A TRANSPOSE OF THIS MATRIX
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[28 15 11]
 [25 13 23]
 [19 24 23]]
(3, 3)


In [55]:
# array=array_name
trans2 = array.T
print(trans2)

[[28 15 11]
 [25 13 23]
 [19 24 23]]


RESHAPING ARRAY

In [56]:
a = np.random.randint(10,30,(3,2))
print(a)

[[16 23]
 [21 27]
 [29 28]]


In [57]:
b = a.reshape(2,3)
print(b)

[[16 23 21]
 [27 29 28]]
